### PR TITLE
chore: Refactor & Support same logic as `DjangoViewSet`

### PR DESCRIPTION
**Pull request by yezz123**
@wu-clan This is the logic I've come up with for #104.

What are your thoughts on using these core logic functions? Additionally, I intend to include documentation and tests.

```py
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, FastAPI

from fastapi_class import HealthCheck, PydanticSerializer, configure_app, register_view
from fastapi_class.views import APIViewSet, L


class PersonSchema(PydanticSerializer):
    id: UUID
    name: str
    age: int


app = FastAPI(
    title="FastAPI Class Example",
    description="Example of FastAPI Class",
    version="0.1.0",
)
router = APIRouter(tags=["Person"])

persons = {}


class MyView(APIViewSet):
    serializer = PersonSchema

    async def list(self) -> L:
        return list(persons.values())

    async def create(self, person: PersonSchema) -> PersonSchema:
        persons[person.id] = person
        return person

    async def retrieve(self, id: UUID) -> Optional[PersonSchema]:
        return persons.get(id)

    async def update(self, person: PersonSchema):
        persons[person.id] = person

    async def destroy(self, id: UUID) -> None:
        try:
            if id not in persons:
                raise KeyError
            persons.pop(id, None)
        except KeyError as e:
            raise ValueError(f"Person with id {id} not found") from e


view = register_view(router, MyView, "/persons")

app.include_router(router)

configure_app(
    app,
    enable_error_handlers=True,
    simplify_openapi_ids=True,
    side_services=None,
    healthcheck=HealthCheck(endpoint="/health"),
)
```

### CODE REVIEW

**Comment by yezz123** [comment]
Hello @wu-clan Sorry for the late response but here is my purpose about this point 

> 1: If implemented in this way, shouldn't we wait for pydantic 2.0?

Merely waiting for the release won't bring any change. Once the release is made, I intend to create a compatible version since not everyone will immediately migrate to it. Hence, I am considering the swift release of a stable version.

> 2: this change may bring greater maintenance costs

To put it concisely, incorporating MVC design in FastAPI would be a seamless process and can be effortlessly integrated with existing frameworks, as I have personally utilized it in my work project.

> 3: fastapi is not like Django binding django-orm, this implementation may affect its popular

While it is undeniable, you may want to consider giving https://github.com/fastapi-mvc/fastapi-mvc a try. It is quite similar, and as you are aware, the endpoint functions follow the ORM or SQL pattern for added support.

> 4: If this solution is implemented, it seems to be called fastapi-class is somewhat controversial?

I am still considering creating this as a separate entity under a new name, such as `fastapi-mvc`.

**Comment by wu-clan** [comment]
The point of view is great. The following is what I want to express.

Fastapi has also just started working on pydantic2.0, can add support later.

I will try fastapi-mvc, and I like mvc architecture very much.

Maybe you can create a new entity or repository and use a new name to keep the existing fastapi-class.

It may take a lot of documents, tests, and examples, such as combining sqlalchemy2.

Finally, have you seen fastapi-crudrouter？

**Comment by yezz123** [comment]
> The point of view is great. The following is what I want to express.
> 
> Fastapi has also just started working on pydantic2.0, can add support later.
> 
> I will try fastapi-mvc, and I like mvc architecture very much.
> 
> Maybe you can create a new entity or repository and use a new name to keep the existing fastapi-class.
> 
> It may take a lot of documents, tests, and examples, such as combining sqlalchemy2.
> 
> Finally, have you seen [fastapi-crudrouter](https://github.com/awtkns/fastapi-crudrouter)？

I agree with you in this point I will try to create a new repository around this

**Comment by wu-clan** [comment]
Thank you for your work. I will be happy to help.

**Comment by yezz123** [comment]
I think I will migrate this to be https://github.com/yezz123/fastapi-lazy

**Pull request closed without merging**
